### ISSUE TITLE
this is persona 5 fusion calc for both persona 5 & royal

### ISSUE THREAD

**Issue by ghost** [Abdool-Zaid/persona_5_web_app#1]

**Comment by ghost** [comment]
i just want to know

**Comment by Abdool-Zaid** [comment]
Hi can you let me know what it is that you would like to know?

**Comment by Abdool-Zaid** [comment]
to provide more context this app was the idea of a friend of mine that we started to develop last week.
this is just the front end of it.
its primary role would be to help players track their progress and plan their way forward.
